[package]
name = "gitp"
version = "0.1.0"
edition = "2021"

[dependencies]
encoding_rs = "0.8.34"
serde = { version = "1.0.200", features = ["derive"] }
serde_yaml = "0.9.34"

[package.metadata]
rustc-version = "1.78.0"

